name: Build BoyCash APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Project
        run: unzip boycash_project.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Accept Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build Android
        run: |
          GRADLE_PATH=$(find . -name gradlew | head -n 1)
          chmod +x "$GRADLE_PATH"
          cd $(dirname "$GRADLE_PATH")
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BoyCash-App
          path: "**/app-debug.apk"
          
