name: Build BoyCash APK
on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Project
        run: |
          unzip -o boycash_project.zip -d temp_folder
          find temp_folder -maxdepth 4 -name "build.gradle" -exec dirname {} \; | xargs -I {} cp -r {}/. .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: |
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BoyCash-App
          path: "**/build/outputs/apk/debug/*.apk"
          
